### ISSUE TITLE
Liberação do código fonte para contribuições?

### ISSUE THREAD

**Issue by danilopcarlotti** [lfcnassif/IPED#10]
Prezado,

Antes de mais nada parabéns pelo trabalho. Gostaria de saber se há interesse na liberação do código para que outras pessoas possam contribuir.
Há algumas visualizações e análises que poderiam ser feitas, por exemplo, com teoria dos grafos aplicadas aos contatos realizados, mensagens encontradas, etc. Além disso, com o código seria possível integrar bibliotecas que fazem vetorização de palavras para aumentar o escopo da pesquisa de regex. Enfim, há várias contribuições possíveis. Peço pra saber se há interesse na abertura do código para, então, fazer essas contribuições.
Muito obrigado,
Danilo

**Comment by lfcnassif** [comment]
Olá Danilo,

Pretendemos sim, obrigado pelo interesse em colaborar. Estamos definindo algumas questões como repositório, modelo de contribuicao etc. Avisamos qdo estiver tudo definido e configurado.

**Comment by lfcnassif** [comment]
Code Published! Lot of work related to translation, API refactoring and documentation. Thanks very much for your interest in collaboration!
