### ISSUE TITLE
Files are exported with original extension instead of detected one in IPED 3.16.3

### ISSUE THREAD

**Issue by LeonardoDiasRR** [lfcnassif/IPED#101]
html chat files are exported without ".html" extension in IPED 3.16.3

**Comment by lfcnassif** [comment]
Hi @LeonardoDiasRR, what do you mean by "exported"? Exported to indexed html report ou exported by right click menu in GUI? Do you refer to chats decoded by UFED or by internal WhatsApp/Skype parsers?

**Comment by tc-wleite** [comment]
@LeonardoDiasRR, do these chat files have any extension? (I mean, their items in your case)

Not sure if it is related, but we had several cases here where files originally have no extension (or wrong extension). 
IPED correctly identified their type. 
But when these items were exported, the original (wrong or absent) extension was used.
In most of these cases I mentioned, the items came from an Apple backup. 
But it can happen with any file without (or with wrong) extension.

The suggestion would be adding an option, when exporting, to allow replacing the original extension when it is wrong and/or absent.
As there are already many export options already (six of them in the main menu), the idea was to have a single "Export..." option, that would open a dialog with all options. 
That would also allow better (longer) description of each option and adding new options (e.g. using the item hash as the file name).

**Comment by lfcnassif** [comment]
ok i understood this is related to GUI export option. @tc-wleite do you think just using the detected extension is sufficient for now?

**Comment by tc-wleite** [comment]
Yes, using the detected extension would solve the issue I described. 
The reason that I suggested an explicit option was to keep the current export behavior as the default (i.e. preserve the original file extension).
Perhaps it would make more sense to use the detected extension as default, and later add an option to preserve the original extension (in case you think that an export dialog is a reasonable idea).

**Comment by lfcnassif** [comment]
Sure, a dialog with export options is better, but I think using the detected ext by default makes more sense, although it will change behaviour.

**Comment by lfcnassif** [comment]
I kept past behaviour when exporting to zip, because that was developed to collect files at crimes scenes, so it is importante to keep original ext in those scenarios, ok @tc-wleite ?

We can open other issue to track the export dialog implementation...

**Comment by tc-wleite** [comment]
Sure, makes sense!
I will create another issue for the export dialog.
