### ISSUE TITLE
Minor bug when copying a cell content with highlighted text

### ISSUE THREAD

**Issue by tc-wleite** [lfcnassif/IPED#111]
A minor bug: when copying the content of a cell from the item table, using CTRL+C, it is not cleaning the HTML terminator as expected, when the cell content has highlighted text.
Example:
![image](https://user-images.githubusercontent.com/7217001/83663871-9f58c700-a59f-11ea-9f67-5378ae0ce3b7.png)
It should copy "SOFTWARE-Report", but it is copying "SOFTWARE-Report<**/html**>".

**Comment by lfcnassif** [comment]
Thank you!
