### ISSUE TITLE
Dynamic layout of frames extracted from videos

### ISSUE THREAD

**Issue by tc-wleite** [lfcnassif/IPED#113]
Currently it is possible to set up the number of frames that will be extracted from video files and will be used to generate a preview image. It is also possible to set up how these frames will be layout in the image (the number of rows and columns). The default configuration uses 4 columns and 5 rows.

Although this configuration seems to be the best for most videos, depending on the **visualizer's screen layout** and the **video aspect ratio** (e.g. ultra wide, portrait orientation) may result in under-utilization of visualizer area, making hard to see the details of video frames.

Two sample screenshots of bad combinations of screen layout and video aspect ratio:
![image](https://user-images.githubusercontent.com/7217001/83687011-8b25c180-a5c1-11ea-92a5-7f625c2bfd16.png)
![image](https://user-images.githubusercontent.com/7217001/83687032-92e56600-a5c1-11ea-98f6-25a68e27dd08.png)

My **suggestion is to dynamically** (when loading a new image) **adjust the layout of extracted frames, so the used area is maximized**, while keeping the maximum amount of video frames visible. 
Although the VideoThumbTask generates a single image with all frames already in the specified layout, it saves metadata information about the frames' layout (this is already used by the HTMLReportTask). So it wouldn't be necessary to change anything in the VideoThumbTask.

The same example images, using the suggested dynamic layout would look like this:
![image](https://user-images.githubusercontent.com/7217001/83688111-3edb8100-a5c3-11ea-84fb-a8c824658d4a.png)
![image](https://user-images.githubusercontent.com/7217001/83688138-4b5fd980-a5c3-11ea-8b89-7b22479766ff.png)

@lfcnassif, my suggestion is to implement this as the default behavior. It is possible to create a parameter to enable/disable this, although I don't think it is necessary. 
Let me know what you think.

**Comment by lfcnassif** [comment]
Thanks @tc-wleite! I can't imagine a scenario when this will not be desirable, so no need for disable parameter for me too.
