### ISSUE TITLE
Arquivo *.iped

### ISSUE THREAD

**Issue by claudemiraraujo** [lfcnassif/IPED#3]
No manual, no tópico processsamento, informa-se que " -d: dados diversos (pode ser usado varias vezes): pasta, imagem DD, 001, E01, AFF (apenas linux), ISO, disco físico, ou arquivo *.iped (contendo seleção de itens a exportar e reindexar)". Qual o formato de um arquivo *.iped? Que tipos de itens eu posso ter nesse arquivo? Nomes de arquivos? Nomes de pastas? Obrigado.

**Comment by lfcnassif** [comment]
Olá Claudemir. Esse arquivo é um formato próprio do iped gerado durante a análise dentro da pasta indexador. Ao processá-lo, todos os itens selecionados na análise são exportados para um reletório html e reindexados.
Se pretende realizar uma exportação automática de dados, dê uma olhada no arquivo conf/CategoriesToExport.txt
