### ISSUE TITLE
Allow image rotation in the viewer

### ISSUE THREAD

**Issue by tc-wleite** [lfcnassif/IPED#45]
Sometimes it is useful to rotate images that contain rotated text (e.g. scanned documents with wrong orientation).
My suggestion is to add a small vertical toolbar to the image viewer, which would only be visible when the mouse is inside the viewer area, to avoid wasting space.
The rotation would be available with two buttons: rotate right, rotate left.
As there will be a toolbar, I suggest also adding two basic functions:
1. Zooming buttons (in, out, and fit-to-window), as an alternative way to control zoom (other than existing mouse scroll button).
2. A slider to control image brightness (useful for dark images).

**Comment by lfcnassif** [comment]
Cool! Thanks, Wladimir! If you could add page navigation for TIFs, that would be great! Take a look at TIFViewer, I think it could be merged in just one image viewer, maybe.

As an optional step, it would be useful to do some abstraction to be used by other kind of documents. For example, there is an incomplete PDFBoxViewer with only page navigation that could use rotation and zoom too.

Thank you very much.

**Comment by tc-wleite** [comment]
Analyzing TIF and PDF viewers you mentioned, I noticed that there are many common parts between them (and also among them and ImageViewer).
I also noticed that TIF viewer lacks a zoom utility. These files are not very common nowadays but zooming may be essential for some images (or the viewer area is too small).
On the other hand, the way TiffViewer reads files is completely different from the ImageViewer.
My current thought is to make the changes to ImageViewer first, then transform TIffViewer to extend of ImageViewer, with specialized methods to read files and handle multiple pages.
Another observation, single page TIF images are quite common. Currently it shows the page navigation controls, which could be suppressed in such cases (so it would look like as any other image to the user).

**Comment by lfcnassif** [comment]
Yes, PDFBoxViewer was based on TIFViewer :) I didn't have time to do the abstraction, it is an incomplete work. Actually IcePDFViewer is used for PDFs today.

Updating TIFViewer to extend ImageViewer seems great!

**Comment by tc-wleite** [comment]
@lfcnassif , made more tests here, the toolbar options seem to be working as expected.
The problem I am facing is that it would steal some space from the viewer area.
I tried a few options of hiding or placing it on different locations, but didn't like any of those. 
In fact the only "nice" solution I found depends on #55, as it would easily allow to place a button in the viewer tab to hide/show the toolbar. 
Other than that, if Docking Frames is used by the viewer tabs, controls currently above the viewer area (hit navigation, checkbox to fix the viewer) could be moved too, reclaiming the space "lost" by the image toolbar.
Any thoughts?

**Comment by lfcnassif** [comment]
I think we can merge this feature for now and update it later after #55 is resolved. Currently the PDFViewer displays a lot of controls too, stealing some space, so ImageViewer will not be the first...

**Comment by lfcnassif** [comment]
@tc-wleite I have not tested #74 yet, but one thing I thought in the past, after image zoom in, is to allow moving/translate the image using mouse move (keeping left button pressed), instead of using scrollbars, I think that is more intuitive to users. I don't know if you have already implemented that...

**Comment by tc-wleite** [comment]
I haven't implemented that, but I think it does make sense as currently there is no action assigned mouse click/drag events. And it is kind of a standard behavior on many image viewers/editors nowadays.
Will try add that as soon as possible, so when you review #74 this is also included.

**Comment by lfcnassif** [comment]
Resolved by #74
