### ISSUE TITLE
Dependência da imagem

### ISSUE THREAD

**Issue by claudemiraraujo** [lfcnassif/IPED#5]
Bom dia.
Após a indexação do caso, sempre necessitarei da imagem, por exemplo, E01, para poder visualizar os arquivos? Em qual arquivo de configuração eu posso indicar o caminho da imagem, caso a mude de local?

**Comment by lfcnassif** [comment]
Sim, após o processamento padrão a imagem forense é necessária para acessar diversos itens. É possivel alterar a localização da imagem no arquivo sqlite sleuth.db, tabela tsk_image_names.
Entretanto, no modo de extração automática de dados, habilitado em conf/CategoriesToExport.txt, os itens especificados são extraídos automaticamente da imagem, a qual se torna desnecessária após o processamento.

**Comment by lfcnassif** [comment]
Fechando pois não se trata de bug.
