### ISSUE TITLE
Add an easier way to change the number of thumbnail columns in the gallery.

### ISSUE THREAD

**Issue by tc-wleite** [lfcnassif/IPED#53]
Add an alternative (easier) way to change the number of columns displayed in the thumbnail gallery.
Currently this option is available as an item application menu.
My suggestion is to use a nice feature called “Action” available in the DockingFrames library. 
It allows associating controls (e.g. buttons) to a “dockable” element, in this case the “Gallery”. These controls are shown in its title bar, close to the already existing window controls.  
This feature (adding buttons to the title bar) is used by several applications (like Eclipse).
Whenever the gallery is active, it would be possible to change the number of thumbnail columns directly.
In my tests, this feature works better with small icon buttons (without text), so it would use tooltips.
If this option works fine, in the future, the current way of changing the number of thumbnail columns could be removed from the menu, as it contains a large number of items already.
An example from the library manual:
![dockable-actions](https://user-images.githubusercontent.com/7217001/77253192-834bb780-6c37-11ea-885e-bc12a1f38f91.png)

**Comment by lfcnassif** [comment]
That is more intuitive!

**Comment by tc-wleite** [comment]
After using the buttons in actual cases, I think the initially implemented way "-" for less columns and "+" for more columns is counterintuitive.
This could be easily reverted, but my suggestion is to use "-" for making thumbnails smaller and "+" for making them bigger.

**Comment by fmpfeifer** [comment]
> 
> 
> After using the buttons in actual cases, I think the initially implemented way "-" for less columns and "+" for more columns is counterintuitive.
> This could be easily reverted, but my suggestion is to use "-" for making thumbnails smaller and "+" for making them bigger.

I tested it here, it's very good and very useful.
But the "-" for less columns and "+" for more columns is indeed counterintuitive for me. I think it shoud be "+" for making the thumbnail bigger and "-" to the other way around.

**Comment by fmpfeifer** [comment]
not a big deal, though
