### ISSUE TITLE
Use DockingFrames in viewer tabs

### ISSUE THREAD

**Issue by tc-wleite** [lfcnassif/IPED#55]
@lfcnassif was there any reason the viewer tabs were not converted to use Docking Frames library?
It could be useful to detach and move one of the viewers.

**Comment by lfcnassif** [comment]
No, just not implemented by original contributor @fmpfeifer. I have already thought about that months ago.

**Comment by fmpfeifer** [comment]
> No, just not implemented by original contributor @fmpfeifer. I have already thought about that months ago.

Adding to my TODO List

**Comment by tc-wleite** [comment]
Hi @fmpfeifer!
Although this is low priority, I implemented other minor feature #45 that is somewhat related.
It would be easier for you to implement this one, but I guess I would be able to implement myself, if you don't mind and have other higher priority stuff to deal with.

**Comment by fmpfeifer** [comment]
Hi @tc-wleite, feel free to implement it. Removing from my TODO List :-)
Thanks

**Comment by tc-wleite** [comment]
@lfcnassif, analyzing the code in more detail, I realized that in the current implementation, a single control (CompositeViewer) contains all viewer. It has the concept of “current selected viewer”, which wouldn’t make sense if viewer tabs can be detached and more than one viewer can be active at the same time. 
I do think the proposed enhancement is something nice to have, as it would give the same flexibility already present in all other components of user interface.  
But that would require a non-trivial refactoring, removing (or moving to iped-app) a lot of functions currently implemented by CompositeViewer (and other classes in iped-viewers).
What do you think about that? Is it worth the effort?

**Comment by lfcnassif** [comment]
@tc-wleite I think so. It will integrate much better with current UI. I thought about scenarios in which user could view "Preview" at same time as "Metadata" or "Text". Also, I think "Occurrences" tab could be in viewer group, cause it shows file content, but displaying it simultaneously has advantages...

I think it will still need concepts of selectedViewer and bestViewer when viewers are together, in default layout. And @fmpfeifer started to implement a VLCViewer that could take advantage of this fearure in some scenarios.

**Comment by tc-wleite** [comment]
@lfcnassif, thanks for the reply!
Yes, this feature can be useful in many situations.
My idea was to keep the concepts of selected and best viewer, when viewers are "grouped", and in fact to keep as much as possible of the current behavior.

I will start to work on it as soon as possible, and will contact you if any questions arise.

**Comment by lfcnassif** [comment]
Merged, thank you @tc-wleite !
