### ISSUE TITLE
Use classic rectangular tabs instead of curved ones, to save space.

### ISSUE THREAD

**Issue by tc-wleite** [lfcnassif/IPED#56]
Currently the dockable tabs waste a lot of horizontal space because of their "curved" aspect. 
@lfcnassif , do you have a personal preference or any other reason to keep this particular feature of the current look (Docking Frames Eclipse theme)?!
 
In smaller screens, this can be annoying as the divider between the left and the central controls can't be moved too far to the left without hiding one of the tab titles (e.g. Categories / Evidences).

My suggestion is to change it to use classic rectangular tabs and with reduced insets, as can be seen in the lower part of the picture.
![CurvedTabs](https://user-images.githubusercontent.com/7217001/77259568-151bea80-6c61-11ea-9049-95a5a78d3fe6.png)

**Comment by lfcnassif** [comment]
Saving space is good, I have no preference! But I remember of an old commit message of @fmpfeifer pointing that he managed something to work just with eclipse theme. Do you remember @fmpfeifer?

**Comment by tc-wleite** [comment]
My suggestion was to keep Eclipse theme! It looks nice and everything is working as expected.
It would be just a minor customization, reducing the space wasted by current curved tabs.

**Comment by lfcnassif** [comment]
Ah ok, I misunderstood. Let's do it.
