### ISSUE TITLE
Problem with -ocr option

### ISSUE THREAD

**Issue by rafael844** [lfcnassif/IPED#6]
Estou tentando usar o -ocr mas não estou conseguindo, poderia mostrar a sintaxe? Estou fazendo como abaixo, mas o resultado não está indexando:
java -jar iped.jar -d S:\teste2\IPED\marcados\03-01.iped -ocr Documentos -o S:\teste2\IPED\teste-03-01.

Outra dúvida, há como marcar o -ocr para somente alguns ítens marcados? Algo tipo ... [-ocr marcador1] ?

Grato.

**Comment by lfcnassif** [comment]
O OCR precisa ser habilitado em IPEDConfig.txt, parâmetro enableOCR. A opção -ocr serve justamente para restringir o OCR a um marcador ou categoria específicos, caso haja mais de um, basta utilizar o -ocr múltiplas vezes.

**Comment by rafael844** [comment]
Bom dia, com o ocr habilitado estou conseguindo fazer  o procedimento completo, mas não com apenas alguns marcadores. Estou fazendo da seguinte forma:
- Salvando um marcador, 03-01.iped, com dois marcadores/tags (sem_ocr, para_ocr)
executando:
java -jar iped.jar -d S:\teste2\IPED\marcador\03-01.iped -ocr para_ocr -o S:\teste2\IPED\teste-03-01

Sem sucesso.

**Comment by lfcnassif** [comment]
Sorry for the long delay. Will test next week

**Comment by lfcnassif** [comment]
Thank you for reporting this. The issue was reproduced and fixed in master branch. The fix will be available in the next release.
