### ISSUE TITLE
Regex validators for more cryptocurrencies

### ISSUE THREAD

**Issue by lfcnassif** [lfcnassif/IPED#66]
Currently just bitcoin is validated to remove false positives, others are disabled, except monero, because they don't have validators and collect lots of garbage. We should do some research and implement others. Found this for ethereum and base58 variances (bitcoin and others?):

https://github.com/joeblackwaslike/coinaddr/blob/master/coinaddr/validation.py

**Comment by fmpfeifer** [comment]
Bitcoin addresses can be encoded both in base58 (addresses begining with 1 (P2PKH) and 3 (P2SH)) or base32 (addresses begining with bc1 (Besh32). All of them are already validated in IPED.

**Comment by lfcnassif** [comment]
Thank you for the explanation, @fmpfeifer!

**Comment by lfcnassif** [comment]
Merged validation for bitcoin cash, ethereum and ripple adresses. Thank you @fmpfeifer

**Comment by lfcnassif** [comment]
Closing this, we can open new tickets for new coins.
