### ISSUE TITLE
Barra de navegação vertical da página tabela não aparece

### ISSUE THREAD

**Issue by claudemiraraujo** [lfcnassif/IPED#8]
Boa tarde.
Processei um caso com sucesso, mas, na visualização pela "ferramenta de pesquisa.exe" a barra de navegação vertical das abas Tabela e Galeria não aparece. Segue tela onde ocorre o erro.

![image](https://user-images.githubusercontent.com/20364360/32666366-4e1fd292-c61e-11e7-9e66-632e5add7e89.png)
Att.
Claudemir

**Comment by urielrodrigues** [comment]
Bom dia, onde consigo realizar o download da ferramenta?

Obrigado.

*Atenciosamente,*

*Uriel Rodrigues*
______________________________________________
*Obrigado por considerar o impacto ambiental de imprimir e-mails. *

Em 10 de novembro de 2017 13:56, claudemiraraujo <notifications@github.com>
escreveu:

**Comment by lfcnassif** [comment]
Olá Claudemir. Esse é um bug do Java: https://bugs.openjdk.java.net/browse/JDK-8134828
Em versões mais novas não públicas do IPED o problema foi contornado. Tente atualizar sua versão do Java e veja se resolve.
