### ISSUE TITLE
IPED deleting -wal and -shm sqlite files

### ISSUE THREAD

**Issue by fmpfeifer** [lfcnassif/IPED#87]
When indexing data from a folder, if there are sqlite files with -wal and -shm files, those files can be deleted by IPED.
Steps to reproduce: 

- create a folder with valid sqlite files with -wal and -shm files (folder dbFiles);
- save a list of all files in the dbFolder;
- index that folder (iped.exe -d dbFiles -o IPED_INDEX)
- check the dbFiles folder for missing -wal and -shm files

**Comment by lfcnassif** [comment]
This was introduced in #21. It affects 3.17.2, maybe I will roll a new release after the fix.
