### ISSUE TITLE
Problem with 3gp exporting

### ISSUE THREAD

**Issue by claudemiraraujo** [lfcnassif/IPED#9]
Boa tarde. 
Processei com sucesso um caso no IPED. Configurei para exportar todas as categorias exceto:
#Peer-to-peer
#Arquivos OLE
#Registro do Windows
#Programas e Bibliotecas
#Tamanho Zero
No IPED, selecionei os arquivos 3gp, todos com tamanho maior que 0 e não deletados e mandei exportar para uma pasta no meu computador. Todos eles foram copiados com tamanho 0, que certamente como verifiquei na listagem do próprio IPED e na própria mídia original, não estavam deletados e não possuem tamanho 0, pois os visualizei com o Encase. Será que houve problema na importação dos arquivos pelo IPED?

**Comment by lfcnassif** [comment]
Please, try the latest 3.17-rc3 version to see if the problem still exists.

**Comment by lfcnassif** [comment]
Not reproducible with 3.17-rc3, closing. Please reopen if the issue still exists with that version.
